<?php
// app/design/frontend/base/default/template/custompaymentmethod/redirect.phtml
$order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);
?>
<?php //echo "string"; ?>
<?php //var_dump($order->loadByIncrementId($orderId)); ?>
<h2><?php echo $this->__('Complete Order Now') ?></h2>
<p><strong>Click "Complete Order" button. Payment can take up to 24 hours to process your card. :-)</strong></p><br>
<form name="custompaymentmethod" method="post" action="<?php echo Mage::helper('custompaymentmethod')->getPaymentGatewayUrl(); ?>">
  <input type="hidden" name="orderId" value="<?php echo $orderId; ?>">
  <input class="button" type="submit" value="<?php echo $this->__('Complete Order') ?>" />
</form>
